# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [1]:
import numpy as delta
x=delta.zeros((1,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Create an array of 10 ones

In [4]:
x= delta.ones((1,10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### Create an array of 10 fives

In [3]:
x = delta.full((1,10), 5, dtype=float)
print(x)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


#### Create an array of the integers from 10 to 50

In [4]:
import numpy as delta
x=delta.arange(10,50,1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50

In [5]:
x=delta.arange(10,50,2)
print(x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
x=delta.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(x)


[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


#### Create a 3x3 identity matrix

In [2]:
import numpy as delta
x=delta.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [10]:
x=delta.random.randn(1)
print(x)

[0.03917745]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
x=delta.random.randn(1,25)
print(x)

[[-0.25128075 -0.52932519  0.89491983 -0.26095949 -0.88529521 -0.20140027
   0.21499226  0.74903693  0.21145053 -0.72728274  1.67705952  0.13647151
  -0.4784366   0.52796836 -0.06586434 -0.97895732  1.35989908 -0.77157295
  -0.49585265  1.62531024  0.73385854 -0.51649759 -0.26124857 -0.23263154
   0.4470666 ]]


#### Create the following matrix:

In [27]:
x=delta.arange(0,1,0.01)
print(x)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [35]:
import numpy as delta
x=delta.linspace(0,1,20)
print(x)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [40]:
import numpy as delta
x=delta.array

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [2]:
import numpy as a
x=a.array([10,20,30,40,50])
print(x[1])

20


In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [3]:
x=a.array([[2],[7],[12]])
print(x)

[[ 2]
 [ 7]
 [12]]


In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [5]:
x=a.array([21,22,23,24,25],dtype='int')
print(x)

[21 22 23 24 25]


In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [6]:
x=a.array([[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
print(x)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [12]:
import numpy as a
x=a.array([[1,2,3],[4,5,6]])
y=a.sum(x)
print(y)

21


#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

In [30]:
import numpy as delta
x=delta.array([55,60,70,75])
y=a.sum(x)
print(y)

260


import numpy as np
arr = np.array([[1, 2, 3, 4]
                 [5, 6, 7, 8]
                 [9, 10, 11, 12]]
a. Retrieve the element at the second row and third column. 
b. Slice the subarray containing the first two rows and the last two columns. 
c. Calculate the sum of each column in the array.)

Generate a 3x3 matrix of random integers between 1 and 100. Calculate the mean and standard deviation of the matrix.

Create a NumPy array with 100 random integers between 1 and 50. Find and print the elements that are greater than 30.

In [36]:
import numpy as a
x=a.random.rand(1,50,100)
print(x)

[[[0.56489203 0.84110171 0.5094155  ... 0.8219557  0.57286285 0.14961463]
  [0.89367628 0.84560939 0.10402096 ... 0.14125462 0.01255108 0.71347113]
  [0.27816388 0.27411074 0.03581992 ... 0.09563545 0.75652289 0.91937443]
  ...
  [0.3410243  0.69545118 0.91166406 ... 0.94781102 0.18849077 0.83791587]
  [0.86821797 0.48089516 0.03684685 ... 0.9527997  0.21236348 0.42812519]
  [0.8128768  0.41201904 0.54318254 ... 0.52487062 0.1574714  0.96161829]]]


A = np.array([[1, 2, 3],              
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
a. Compute the matrix multiplication of A and B. 
b. Calculate the determinant of matrix A. 
c. Find the eigenvalues and eigenvectors of matrix B.

Certainly! Here are a few NumPy-related questions of varying difficulty levels: 
 
Question 1: Array Operations 
 
Create a NumPy array arr with elements from 1 to 10 (inclusive). Perform the following operations: 
 
a. Square each element of the array. 
b. Calculate the mean of the squared array. 
c. Reshape the array to a 2x5 matrix.

Create a NumPy array with values ranging from 1 to 10.  
  
Create a 3x3 matrix with values ranging from 0 to 8.  
  
Create a 2x2 identity matrix.  
  
Generate a random 4x4 matrix and find the minimum and maximum values in it.  
  
Create a 5x5 matrix with values 1, 2, 3, 4 just below the main diagonal.  
  
Given a 1D array, negate all elements that are between 3 and 8, in place.  
  
Create a 2D array of shape (5, 5) with decimal numbers and round each element to the nearest integer.  
  
Create a random 5x5 matrix and normalize it by subtracting the mean and dividing by the standard deviation along each row. 
Generate a 1D array of 10 equally spaced values between 0 and 1, inclusive.

In [2]:
import numpy as a
x=a.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [11]:
x=a.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
x=a.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
x=a.array([[[[1,21,22,13,45,]]]])
y=x.min()
z=x.max()
print(y,z)


1 45


In [22]:
import numpy as a
values = [1, 2, 3, 4]
matrix = a.diag(values)
print(matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [31]:
x=a.random.rand(1,25).reshape(5,5)
print(x)

[[0.28598614 0.85251234 0.04636339 0.7794924  0.64439488]
 [0.92438446 0.03437386 0.70954011 0.1344042  0.48598143]
 [0.7175704  0.42915379 0.87482431 0.93003607 0.45800578]
 [0.13038051 0.72745715 0.97924614 0.17531755 0.92726909]
 [0.34595152 0.06197581 0.51103524 0.59199815 0.47325493]]
